name: deploy

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Update project
        run: |
          cd /home/eloriente/actions-runner/_work/plex-homeserver/plex-homeserver
          git pull origin main
          cp .env.template .env
          
      - name: Docker run
        run: |
          cd /home/eloriente/actions-runner/_work/plex-homeserver/plex-homeserver
          docker builder prune -f && docker compose up -d --build
